# Ci is created when we just creating the PR on push or pull 
#CD pipeline created when there is if commited in production after 2 weeks from another branch to main branch they do check CD 
#pipeline 
name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install
        
      - name: Run Build
        run: npm run build
